title: The Title
author: ME
email: the-dude@bides.com
description: > # this means to ignore newlines until "baseurl:"
  some wicked cool metadata to allow weird people to discover me.

# social links
twitter_username: kaleiopedesign
github_username:  pwflint

show_excerpts: false # set to true to show excerpts on the homepage

theme: minima
